language: node_js
node_js:
  - "11.10.1"
install:
  - npm install
before_script:
  - export CODE_COVERAGE_TOKEN=$CODE_COVERAGE_TOKEN
  - export HEROKU_KEY=$HEROKU_KEY
script:
  - npm run write-coveralls
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: traineru
  on: master
  strategy: git
